# Generated by Django 4.2.16 on 2024-11-11 08:39

from django.db import migrations, models
import nems_proctor.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_baseimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baseimage",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AlterField(
            model_name="baseimage",
            name="image",
            field=models.ImageField(
                upload_to=nems_proctor.users.models.get_base_image_path,
                validators=[nems_proctor.users.models.validate_image],
            ),
        ),
    ]
