# Generated by Django 4.2.16 on 2024-11-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_baseimage_options_alter_baseimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseimage",
            name="image_base64",
            field=models.BinaryField(
                help_text="Base64 encoded image data for Rekognition",
                null=True,
                verbose_name="Base64 Image Data",
            ),
        ),
    ]
